[B2BP-112] - Created page documenti
pagopa/pn-showcase-site pull request #16
Opened 2023-11-02 16:07 UTC by salvatorediocaro

Description
Created the "documenti" page

List of Changes
To create the "documenti" page, the "PD.tsx" was created and "index.tsx", "default.css", "navigationBar.tsx", "it.tsx" files were modified

Motivation and Context
Create a new page 

How Has This Been Tested?
Execute on locally the SEND Site

Screenshots (if appropriate):

Types of changes
New feature (non-breaking change which adds functionality)

Checklist:
My change not requires a change to the documentation.

2023-11-09 14:17 UTC, ZorbaDimatteo requested changes
@salvatorediocaro oltre ai commenti, è necessario pullare da develop e risolvere i conflitti

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
@salvatorediocaro aggiungi il link al manuale operativo
https://docs.pagopa.it/manuale-operativo/

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
@salvatorediocaro usa questo link per le api b2b 
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pn-delivery/pn-openapi-prod/docs/openapi/api-external-b2b-pa-bundle.yaml

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    label: "Vai alle API B2B per l’avanzamento delle notifiche",
@salvatorediocaro questo item non serve più, si può eliminare

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
cambia la label in "API b2b per le pubbliche amministrazioni e per l'avanzamento delle notifiche"

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
@salvatorediocaro link al documento https://docs.pagopa.it/documento-4-ciclo-attivo-pn

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
il modulo di profilazione è un pdf presente negli assets
com'era
```
<Link 
                  href={"/static/documents/Modulo preventivo di fornitura.xlsx"}
                  aria-label="Modulo di Profilazione"
                >
```

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
@salvatorediocaro anche per il modulo di commessa 
 ```
<Link 
                  href={
                    "/static/documents/Modulo Ordinativo Commessa per Anticipazione.xlsx"
                  }
                  aria-label="Modulo Commessa"
                >
```

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                    link: "#",
link alle SLA https://docs.pagopa.it/sla-di-servizio/

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                                    <Link href="/faq"
il link delle faq corretto è https://docs.pagopa.it/faq-enti

2023-11-09 14:17 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                                    Aderisci a SEND
questo button deve portare all'Area Riservata, aggiungere il link

2023-11-09 14:17 UTC, ZorbaDimatteo commented on styles/default.css
> +
@salvatorediocaro tutte queste modifiche allo style non potrebbero essere riportate solo ai componenti custom della pagina documentazione?
se lasciamo le modifiche che hai fatto tu, tutte le altre future cards prenderanno lo stesso style.
Se necessario puoi creare uno styled component dedicato alle card della pagina di documentazione es "DocumentCard"

2023-11-09 14:44 UTC, salvatorediocaro commented on styles/default.css
> +
ok, modifico le varie classi per funzionare solo nella pagina documentazione

2023-11-17 09:52 UTC, ZorbaDimatteo commented on api/data/it/PD.tsx
> +                                    Aderisci a SEND
@salvatorediocaro il link aggiunto è errato (va su cittadini.notifichedigitali.it) deve andare su https://selfcare.pagopa.it/auth/login?onSuccess=%2Fonboarding%2Fprod-pn

2023-11-17 09:56 UTC, ZorbaDimatteo requested changes
@salvatorediocaro 
nella card "Documentazione Tecnica" sostituire il link "Vai al documento" con il link al developer portal
Tuttavia, sia questo link che il banner "Il tuo ente ha già aderito e hai bisogno di approfondire le fasi di integrazione alla Piattaforma?" vanno "nascosti" perchè il developer portal sarà online il 27 dicembre.
Proporrei di commentarle in questo branch e aprire poi un branch con tutte le modifiche che andranno online il 30 novembre

2023-11-17 14:39 UTC, ZorbaDimatteo approved these changes

2023-11-17 14:40 UTC, merged