Refactor/pn 12178 - Translate common components using translation hook
pagopa/pn-showcase-site pull request #76
Opened 2024-08-06 10:19 UTC by mflauti

This PR refactors the code for the common components (header, menu, footer) of the page structure making use of the translation hook to support multilanguage functionality

2024-08-06 15:00 UTC, AndreaCimini90 requested changes

2024-08-07 09:55 UTC, mflauti commented on src/api/data/it.tsx
> +// import {
ok

2024-08-07 09:56 UTC, mflauti commented on public/locales/en/common.json
> +        "company_info": {
ok

2024-08-07 09:56 UTC, mflauti commented on src/components/Layout.tsx
> +        <NavigationBar title={t('navigation.title')} image={`${IMAGES_PATH}/logo.svg`} />
ok

2024-08-07 09:57 UTC, mflauti commented on src/components/Layout.tsx
> +          // preLoginLinks={preLoginLinks(t, lang)}
ok

2024-08-07 09:57 UTC, mflauti commented on src/components/NavigationBar.tsx
> +    // {
ok

2024-08-07 09:57 UTC, mflauti commented on src/pages/[lang]/punti-di-ritiro/index.dev.tsx
> +      <DarkInfoblockRitiro
ok

2024-08-08 08:13 UTC, AndreaCimini90 approved these changes

2024-08-08 08:28 UTC, AndreaCimini90 requested changes

2024-08-08 08:28 UTC, AndreaCimini90 commented on public/locales/it/common.json
> +    "pickup_points": {
move pickup_points and infoblock_ritiro into a file named ritiro.json

2024-08-08 10:06 UTC, AndreaCimini90 approved these changes

2024-08-08 10:07 UTC, merged