feat: light fix
pagopa/pn-showcase-site pull request #97
Opened 2024-12-16 09:17 UTC by ZorbaDimatteo

2024-12-23 10:26 UTC, SarahDonvito requested changes
in `src/pages/[lang]/punti-di-ritiro/come-funziona.tsx` the route prop is not provided, so there are compiling problems

2024-12-23 12:40 UTC, SarahDonvito requested changes

2024-12-23 12:40 UTC, SarahDonvito commented on public/locales/it/imprese.json
In `infoblock_2.description_1` the sentence "...le comunicazioni potranno essere gestite..." in [Figma](https://www.figma.com/design/64eXbbNjuZI8YwfjWzsGlU/%5BSEND%5D-Sito-vetrina?node-id=4642-19005&t=x68pZQyvCESPMkrL-4) is "le comunicazioni possono essere gestite"

2024-12-23 12:40 UTC, SarahDonvito commented on public/locales/it/imprese.json
>          "cta": "Leggi le tue notifiche"
The walkthrough block is different than [Figma](https://www.figma.com/design/64eXbbNjuZI8YwfjWzsGlU/%5BSEND%5D-Sito-vetrina?node-id=5086-16322&t=x68pZQyvCESPMkrL-4)

2024-12-23 15:17 UTC, SarahDonvito requested changes

2025-01-09 16:50 UTC, ZorbaDimatteo commented on public/locales/it/imprese.json
>          "cta": "Leggi le tue notifiche"
after a check with design team, it appears that the [figma](https://www.figma.com/design/64eXbbNjuZI8YwfjWzsGlU?node-id=4642-18999#1085889972) was wrong

2025-01-09 17:01 UTC, merged